# 
# Synthesis run script generated by Vivado
# 

set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivadoproject/project_2018070901/project_20180708/project_20180708.cache/wt [current_project]
set_property parent.project_path D:/vivadoproject/project_2018070901/project_20180708/project_20180708.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{e:/Personal Documents/Digital-Design-Lab-master/Chapter_12/Digital_camera/files/HDL_source/IP_Catalog}} [current_project]
set_property ip_output_repo d:/vivadoproject/project_2018070901/project_20180708/project_20180708.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/vivadoproject/project_2018070901/project_20180708/welcome.coe
add_files D:/vivadoproject/project_2018070901/project_20180708/welcome2.coe
read_verilog -library xil_defaultlib {
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/Clock_Divider_2.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/FSM.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/boundry_tracking.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/button.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/button1.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/button2.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/button3.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/debounce.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/debounce_vga.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/divide.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/divide_duoshuzi.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/rgb_to_ycbcr.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/shifter.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/shifter_duoshuzi.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/shumaguan.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/shumaguan_duoshuzi.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/top_flyinglogo.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/vga_640x480.v
  D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/new/design_1.v
}
read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/cam_ov7670_ov7725_0/cam_ov7670_ov7725_0.xci
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/cam_ov7670_ov7725_0/cam_ov7670_ov7725_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/ov7725_regData_0/ov7725_regData_0.xci
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/ov7725_regData_0/ov7725_regData_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/vga_0/vga_0.xci
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/vga_0/vga_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/IICctrl_0/IICctrl_0.xci
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/IICctrl_0/IICctrl_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/ram_read_0/ram_read_0.xci
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/ram_read_0/ram_read_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_ip -quiet D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc]
set_property used_in_implementation false [get_files -all d:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc]
set_property is_locked true [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/sources_1/ip/dcm_25m/dcm_25m.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/constrs_1/new/shibir_xdc.xdc
set_property used_in_implementation false [get_files D:/vivadoproject/project_2018070901/project_20180708/project_20180708.srcs/constrs_1/new/shibir_xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef design_1.dcp

catch { report_utilization -file design_1_utilization_synth.rpt -pb design_1_utilization_synth.pb }
